### ISSUE TITLE
Using WEBSITE_SITE_NAME doesn't work for site slots

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-websites-security#2]
in a site called `foo`, `WEBSITE_SITE_NAME == foo` and machine key is in a `<location>` node that looks like

```xml
<location path="foo">
  <system.web>
    <machineKey validationKey="xxxxxxxxx" decryptionKey="xxxxxxxx" decryption="AES" />
  </system.web>
</location>
```
but in a slot for `foo` called `staging`, this is still true  `WEBSITE_SITE_NAME == foo`  but the `<location>` tag looks like 

```xml
<location path="foo__zzzz">
  <system.web>
    <machineKey validationKey="xxxxxxxxx" decryptionKey="xxxxxxxx" decryption="AES" />
  </system.web>
</location>
```

where `zzzz` is 4 random characters. 

consider using `WEBSITE_IIS_SITE_NAME ` instead.

**Comment by fabiocav** [comment]
This has been resolved.
